import { useEffect, useState } from 'react'
import { supabase } from '../../supabaseClient'
import { useSiteSettings } from '../../context/SiteSettingsContext'

export default function AdminSettings() {
  const { reload } = useSiteSettings()
    const [form, setForm] = useState({
        site_name: '',
            logo_url: '',
                hero_title: '',
                    hero_subtitle: '',
                        footer_org_name: '',
                          })
                            const [saving, setSaving] = useState(false)
                              const [loaded, setLoaded] = useState(false)

                                useEffect(() => {
                                    supabase
                                          .from('site_settings')
                                                .select('*')
                                                      .eq('id', 1)
                                                            .single()
                                                                  .then(({ data }) => {
                                                                          if (data) {
                                                                                    setForm({
                                                                                                site_name: data.site_name || '',
                                                                                                            logo_url: data.logo_url || '',
                                                                                                                        hero_title: data.hero_title || '',
                                                                                                                                    hero_subtitle: data.hero_subtitle || '',
                                                                                                                                                footer_org_name: data.footer_org_name || '',
                                                                                                                                                          })
                                                                                                                                                                  }
                                                                                                                                                                          setLoaded(true)
                                                                                                                                                                                })
                                                                                                                                                                                  }, [])

                                                                                                                                                                                    function updateField(key, value) {
                                                                                                                                                                                        setForm((f) => ({ ...f, [key]: value }))
                                                                                                                                                                                          }

                                                                                                                                                                                            async function handleSubmit(e) {
                                                                                                                                                                                                e.preventDefault()
                                                                                                                                                                                                    setSaving(true)
                                                                                                                                                                                                        const { error } = await supabase
                                                                                                                                                                                                              .from('site_settings')
                                                                                                                                                                                                                    .upsert({ id: 1, ...form, updated_at: new Date().toISOString() })
                                                                                                                                                                                                                        setSaving(false)
                                                                                                                                                                                                                            if (error) {
                                                                                                                                                                                                                                  alert('Gagal simpan: ' + error.message)
                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                            reload()
                                                                                                                                                                                                                                                  alert('Branding dikemaskini! Refresh laman utama untuk lihat perubahan.')
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                          if (!loaded) return <p className="text-sm text-gray-500">Memuatkan...</p>

                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                      <h1 className="text-xl font-bold mb-2">Tetapan Branding</h1>
                                                                                                                                                                                                                                                                            <p className="text-sm text-gray-500 mb-6">
                                                                                                                                                                                                                                                                                    Tukar logo, nama laman, tajuk utama & nama organisasi. Simpan terus live, tak perlu coding.
                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                <form onSubmit={handleSubmit} className="bg-white border border-gray-200 rounded-lg p-5 space-y-4 max-w-xl">
                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-medium mb-1">Nama Laman Web (navbar)</label>
                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                    value={form.site_name}
                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => updateField('site_name', e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                            className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-sm font-medium mb-1">URL Logo</label>
                                                                                                                                                                                                                                                                                                                                                                                                                          {form.logo_url && (
                                                                                                                                                                                                                                                                                                                                                                                                                                      <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                    src={form.logo_url}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alt="Logo semasa"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="h-14 w-14 object-contain rounded border border-gray-200 mb-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="https://... (upload gambar ke Imgur/Drive/Cloudinary dulu, paste link di sini)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={form.logo_url}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => updateField('logo_url', e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm font-medium mb-1">Tajuk Utama (halaman depan)</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={form.hero_title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => updateField('hero_title', e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label className="block text-sm font-medium mb-1">Sub-tajuk</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={form.hero_subtitle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => updateField('hero_subtitle', e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rows={2}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm font-medium mb-1">Nama Organisasi (footer)</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={form.footer_org_name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => updateField('footer_org_name', e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={saving}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="bg-brand-600 text-white px-4 py-2 rounded text-sm font-semibold hover:bg-brand-500 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {saving ? 'Menyimpan...' : 'Simpan Perubahan'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }